### ISSUE TITLE
底模推荐

### ISSUE THREAD

**Issue by H9990HH969** [Stardust-minus/Bert-VITS2#1]
你好，请问底模有没有什么推荐？我想训练长文本模型，以前用vits跑下来都不太成功，只能读一些较短的语句

**Comment by Stardust-minus** [comment]
我这边公开了一个底模，https://openi.pcl.ac.cn/Stardust_minus/Bert-VITS2/modelmanage/model_filelist_tmpl?name=Bert-VITS2%E5%BA%95%E6%A8%A1
