### ISSUE TITLE
nameError: name 'transcription_path’is not defined. 

### ISSUE THREAD

**Issue by luguoyixiazi** [Stardust-minus/Bert-VITS2#9]
preprocess_text.py原版是直接定义的文件路径，使用transcription_path这个变量，貌似这一段代码没改，上面的块里面循环的变量在部分情况下不会升到全局吧？不如把这个改成函数运行直接导了传变量进去用，在前面一步先打印可选的文件路径，让小白直接复制就行

**Comment by Stardust-minus** [comment]
PR Welcome
